# Generated by Django 3.2.3 on 2021-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=30)),
                ('brend_name', models.CharField(default='', max_length=30, null=True)),
                ('director_name', models.CharField(default='', max_length=30, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_set', models.BooleanField(default=False)),
            ],
        ),
    ]
